version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app worker -l info
    depends_on:
      - redis
      - db
      - web # Due to db table initialization
    environment:
      - DATABASE_URL
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A celery_app beat -l info
    depends_on:
      - redis
      - db
      - web # Due to db table initialization
    environment:
      - DATABASE_URL
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
